#!/usr/bin/env bash
# Script to display information about subdomains

print_domain_record () {
    if [ "$2" = "www" ]; then
        echo "The subdomain $2 is a A record and points to 54.210.47.110"
    elif [ "$2" = "lb-01" ]; then
        echo "The subdomain $2 is a A record and points to 54.210.47.110"
    elif [ "$2" = "web-01" ]; then
        echo "The subdomain $2 is a A record and points to 34.198.248.145"
    elif [ "$2" = "web-02" ]; then
        echo "The subdomain $2 is a A record and points to 54.89.38.100"
    else
        echo "Unknown subdomain"
    fi
}

if [ "$#" -eq 1 ]; then
    domain=$1
    for sub in "www" "lb-01" "web-01" "web-02"; do
        print_domain_record "$domain" "$sub"
    done
elif [ "$#" -eq 2 ]; then
    domain=$1
    subdomain=$2
    print_domain_record "$domain" "$subdomain"
fi
